server:
  port: 9296
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nidhipandey26/Springboot-Microservices-Project/blob/main/application.yml
            clone-on-start:true